### ISSUE TITLE
if two repositories has same tag names, how does it work

### ISSUE THREAD

**Issue by faizan80** [robinst/git-merge-repos#11]
Hi,
If two repositories that I want to migrate into a new repository, have same tag names.
Are the tags preserved in some way ? 
I want all tags pointing to correct gitSHA in history. 

how does your tool work ?

**Comment by robinst** [comment]
Tags are merged similarly to branches: A new commit is constructed that is a merge of all the commits, and then the tag points to that new commit. Give it a try?

> I want all tags pointing to correct gitSHA in history.

To the original commits? In that case, the tags would have to be renamed so that they don't conflict. This tool doesn't do that, but you can do that by preprocessing your repositories and rename all the tags so that there are no name clashes.
